
title: Physics and code
email: chriscarman@protonmail.com
repository: "shadesfear/shades.github.io"
url: "shadesfear.github.io" 
github_username: shadesfear

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"

author:
  name   : "Christopher Carman"
  avatar : "/assets/images/headshot.jpg"
  bio    : "Writing about the things I enjoy in life, physics programming and good stuff"
  location: "Copenhagen - Denmark"
  github : shadesfear
  linkedin: christopher-carman

comments:
  provider: "disqus"
  disqus:
    shortname: "shadesfear-github-io"
    
paginate: 10 # number of posts to show
paginate_path: /page:num/

defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
