# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Journey
tagline:          'Tagline'
description:      'Description'
url:              https://shadesfear.github.io
baseurl:          /

paginate:         5

