title: Physics and Code
description: My Personal Stack Problems
author: Christopher Carman
github: https://github.com/shadesfear
about: Student of Physics at the University of Copenhagen, exploring programming
disqus_shortname: physcode
google_analytics: UA-XXXXXXXX-Y
theme: minimal-mistakes-jekyll

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/
    
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/christopher-carman/"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/11118251/shadesfear"
    - icon: fa-github
      link: "https://github.com/shadesfear"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/

    - text: XML Feed
      url: /feed.xml

url: "https://shadesfear.github.io"
baseurl: "/"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
